PORT = 8080

RUN_MODE = "release"

MONGO_URI = "mongodb://localhost:27017/"

DB_NAME = "careerCompass"
USER_COLLECTION = "users"

TRANSPORT_EMAIL = "interxview@gmail.com"
TRANSPORT_EMAIL_PASSWORD = ""