PORT = 8080

RUN_MODE = "develop"

MONGO_URI = "mongodb://localhost:27017/"

DB_NAME = "careerCompass"
USER_COLLECTION = "users"
ROLE_COLLECTION = "roles"
SKILL_COLLECTION = "skills"
QUESTION_COLLECTION = "questions"
ANSWER_COLLECTION = "answers"


SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_EMAIL = "careercompass.noreply@gmail.com"
SMTP_PASSWORD = ""

JWT_SECRET = ""

ML_SERVER_URL = "https://mlcareercompass.azurewebsites.net"