PORT = 8080

RUN_MODE = "release"

MONGO_URI = "mongodb://localhost:27017/"

DB_NAME = "careerCompass"
USER_COLLECTION = "users"

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_EMAIL = "interxview@gmail.com"
SMTP_PASSWORD = ""

JWT_SECRET = ""